# This is a workflow to sync between two git branches

name: sync_branch

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]
 # pull_request:
   # branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync_branches:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: wei/git-sync@v2

    # Runs a single command using the runners shell
    - name: Sync two branches
      with:
        source_repo: "https://github.com/genericarati/github_action"
        source_branch: "branch-2"
        destination_repo: "https://github.com/genericarati/github_action"
        destination_branch: "master"
        ssh_private_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnlNB6C4SzNHC8u6kgIOxppLF/DqVIwGWj8DaSVnmbJSJ6GbVmDWr0DEPRpWJYJCpCYJ6c8u8LQezk0UkPe2hNF447bHd58uJvurZX9GmZQe5/q2916Ow7ui1afLYKzdEf87TDRkimAXHy/CcJYZmIVJzZgjKMwt8ZH4MMQA63i3augnzhaWvpVIfHGCN8CJaW60YN/fv2Rwb3Qdzz8QhnVrKoqKGA4CjQVmmw1EY1YEhrGPsbPzIqZFvoHWtuxa+U6Oac9VuS1yaFPJVM0e/QEU5eypNmvgsIA+0QPaWKhigEwHDXH0bsPd5JpL+3nR0pZM60uAudcdafFT/IbRSb aratijoshi@Aratis-MacBook-Pro.local
