name: Sync
on:
  push:
    branches:
      - vouchers-3.1

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "vouchers-3.1"
          TO_BRANCH: "vouchers-4.0"
          PULL_REQUEST_TITLE: "Merge {FROM_BRANCH} to {TO_BRANCH}"
