name: sync_branch
on:
  push:
    branches: [ master ]
jobs:
  sync_branches:
    runs-on: ubuntu-latest
    steps:
    -  name: Sync two branches
       uses: wei/git-sync@v2
       with:
         source_repo: "https://github.com/genericarati/github_action"
         source_branch: "branch-2"
         destination_repo: "https://github.com/genericarati/github_action"
         destination_branch: "master"
         ssh_private_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnlNB6C4SzNHC8u6kgIOxppLF/DqVIwGWj8DaSVnmbJSJ6GbVmDWr0DEPRpWJYJCpCYJ6c8u8LQezk0UkPe2hNF447bHd58uJvurZX9GmZQe5/q2916Ow7ui1afLYKzdEf87TDRkimAXHy/CcJYZmIVJzZgjKMwt8ZH4MMQA63i3augnzhaWvpVIfHGCN8CJaW60YN/fv2Rwb3Qdzz8QhnVrKoqKGA4CjQVmmw1EY1YEhrGPsbPzIqZFvoHWtuxa+U6Oac9VuS1yaFPJVM0e/QEU5eypNmvgsIA+0QPaWKhigEwHDXH0bsPd5JpL+3nR0pZM60uAudcdafFT/IbRSb aratijoshi@Aratis-MacBook-Pro.local
